### ISSUE TITLE
Where is the example?..

### ISSUE THREAD

**Issue by jona-sassenhagen** [benwhalley/signalbox#5]
Trying to set up this very interesting looking project, I stumbled here:

```
git clone GITHUBREPO newname
cd newname
pip install -r requirements.txt
```

Where is the example (GITHUBREPO)? I can't find the `heroku_install_signalbox` script anywhere.

**Comment by jona-sassenhagen** [comment]
Hm, thanks - but that repo doesn't have a script for an easy setup on Heroku, correct?

**Comment by benwhalley** [comment]
Actually, there is an app.json which would enable you to configure an example with from a 'heroku button'... see this page: http://www.thesignalbox.net/deploy/ The problem is that this is now a little outdated as heroku changed some of their package/service names. I don't think it would take long to fix, but if you want to email me (https://github.com/benwhalley) then we can discuss what you're doing and simplest way to get setup.

**Comment by jona-sassenhagen** [comment]
Ok thanks, I will play around a bit and see if I can figure out things on my own, and if not, I might bother you again :(

**Comment by benwhalley** [comment]
Just to update this, I fixed the app.json, so you can install a simple instance on heroku free plan to evaluate pretty much automatically. See http://www.thesignalbox.net/deploy/

**Comment by benwhalley** [comment]
What bad luck... the very latest version of pip, just installed by heroku I think, has broken external use of parse_requirements. I've included the workaround you suggested, so thanks for that.

Would you mind testing again and see how you get on. I have successfully deployed to heroku now using the button, so it should work.

**Comment by jona-sassenhagen** [comment]
Yup, up and running, from what I can tell. Thanks!
